# Generated by Django 3.1.2 on 2020-10-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201031_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='INCOMPLETE', max_length=15),
        ),
    ]
